# Generated by Django 4.2.7 on 2025-09-17 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('instructions', models.TextField(default='You are a helpful AI assistant. You can respond with both text and audio. Keep responses concise and natural.')),
                ('voice', models.CharField(choices=[('alloy', 'Alloy'), ('echo', 'Echo'), ('fable', 'Fable'), ('onyx', 'Onyx'), ('nova', 'Nova'), ('shimmer', 'Shimmer')], default='alloy', max_length=20)),
                ('temperature', models.FloatField(default=0.8)),
                ('max_response_output_tokens', models.CharField(default='inf', max_length=10)),
                ('input_audio_format', models.CharField(default='pcm16', max_length=20)),
                ('output_audio_format', models.CharField(default='pcm16', max_length=20)),
                ('vad_threshold', models.FloatField(default=0.5)),
                ('vad_prefix_padding_ms', models.IntegerField(default=300)),
                ('vad_silence_duration_ms', models.IntegerField(default=200)),
                ('enable_input_transcription', models.BooleanField(default=True)),
                ('transcription_model', models.CharField(default='whisper-1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('twilio_call_sid', models.CharField(blank=True, max_length=100, null=True)),
                ('twilio_stream_sid', models.CharField(blank=True, max_length=100, null=True)),
                ('caller_number', models.CharField(blank=True, max_length=20, null=True)),
                ('call_start_time', models.DateTimeField(auto_now_add=True)),
                ('call_end_time', models.DateTimeField(blank=True, null=True)),
                ('call_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('connected', 'Connected'), ('ended', 'Ended'), ('error', 'Error')], default='started', max_length=20)),
                ('conversation_log', models.JSONField(blank=True, default=list)),
                ('agent_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realtime_api.agentconfiguration')),
            ],
        ),
    ]
