# Generated by Django 4.2.7 on 2025-09-18 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realtime_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfiguration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agentconfiguration',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='agentconfiguration',
            unique_together={('user', 'name')},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_api_key', models.CharField(blank=True, help_text='Your OpenAI API key (starts with sk-)', max_length=200, null=True)),
                ('twilio_account_sid', models.CharField(blank=True, help_text='Your Twilio Account SID (optional, falls back to system default)', max_length=100, null=True)),
                ('twilio_auth_token', models.CharField(blank=True, help_text='Your Twilio Auth Token (optional, falls back to system default)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
