# Generated by Django 4.2.7 on 2025-09-18 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realtime_api', '0002_agentconfiguration_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='called_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='agentconfiguration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Twilio phone number (e.g., +1234567890)', max_length=20, unique=True)),
                ('twilio_phone_number_sid', models.CharField(help_text='Twilio Phone Number SID (starts with PN)', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_config', models.ForeignKey(blank=True, help_text="Agent to use for calls to this number (uses user's default if not set)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_numbers', to='realtime_api.agentconfiguration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phone Number',
                'verbose_name_plural': 'Phone Numbers',
            },
        ),
        migrations.AddField(
            model_name='callsession',
            name='phone_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_sessions', to='realtime_api.phonenumber'),
        ),
    ]
