# Generated by Django 4.2.7 on 2025-09-18 16:55

from django.db import migrations


def update_audio_formats(apps, schema_editor):
    """Update existing agents to use g711_ulaw audio format for Twilio compatibility"""
    AgentConfiguration = apps.get_model('realtime_api', 'AgentConfiguration')
    
    # Update all agents to use Twilio-compatible audio format
    updated_count = AgentConfiguration.objects.filter(
        input_audio_format='pcm16'
    ).update(
        input_audio_format='g711_ulaw',
        output_audio_format='g711_ulaw'
    )
    
    print(f"Updated {updated_count} agents to use g711_ulaw audio format")


def reverse_audio_formats(apps, schema_editor):
    """Reverse: Update back to pcm16"""
    AgentConfiguration = apps.get_model('realtime_api', 'AgentConfiguration')
    
    AgentConfiguration.objects.filter(
        input_audio_format='g711_ulaw'
    ).update(
        input_audio_format='pcm16',
        output_audio_format='pcm16'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_api', '0004_assign_users_to_agents'),
    ]

    operations = [
        migrations.RunPython(update_audio_formats, reverse_audio_formats),
    ]
