# Generated by Django 4.2.7 on 2025-09-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_api', '0005_update_audio_formats_to_twilio'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfiguration',
            name='model',
            field=models.CharField(choices=[('gpt-4o-realtime-preview-2024-12-17', 'GPT-4o Realtime (2024-12-17)'), ('gpt-4o-realtime-preview-2025-06-03', 'GPT-4o Realtime (2025-06-03)'), ('gpt-4o-realtime-preview-2024-10-01', 'GPT-4o Realtime (2024-10-01)'), ('gpt-4o-mini-realtime-preview-2024-12-17', 'GPT-4o Mini Realtime (2024-12-17)'), ('gpt-4o-mini-realtime-preview', 'GPT-4o Mini Realtime'), ('gpt-realtime', 'GPT Realtime')], default='gpt-4o-realtime-preview-2024-12-17', help_text='Choose the OpenAI Realtime model for this agent', max_length=50),
        ),
        migrations.AlterField(
            model_name='agentconfiguration',
            name='input_audio_format',
            field=models.CharField(default='g711_ulaw', max_length=20),
        ),
        migrations.AlterField(
            model_name='agentconfiguration',
            name='output_audio_format',
            field=models.CharField(default='g711_ulaw', max_length=20),
        ),
        migrations.AlterField(
            model_name='agentconfiguration',
            name='transcription_model',
            field=models.CharField(choices=[('whisper-1', 'Whisper-1'), ('gpt-4o-mini-transcribe', 'GPT-4o Mini Transcribe'), ('gpt-4o-transcribe', 'GPT-4o Transcribe')], default='whisper-1', help_text='Choose the transcription model for speech-to-text', max_length=50),
        ),
        migrations.AlterField(
            model_name='agentconfiguration',
            name='voice',
            field=models.CharField(choices=[('alloy', 'Alloy'), ('ash', 'Ash'), ('ballad', 'Ballad'), ('cedar', 'Cedar'), ('coral', 'Coral'), ('echo', 'Echo'), ('marin', 'Marin'), ('sage', 'Sage'), ('shimmer', 'Shimmer'), ('verse', 'Verse')], default='alloy', max_length=20),
        ),
    ]
