# Generated by Django 4.2.7 on 2025-09-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_api', '0006_add_model_and_transcription_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfiguration',
            name='vad_eagerness',
            field=models.CharField(choices=[('low', 'Low - Let user take their time'), ('medium', 'Medium - Balanced (default)'), ('high', 'High - Interrupt as soon as possible'), ('auto', 'Auto - Same as medium')], default='auto', help_text='How eager the model is to interrupt the user (semantic VAD only)', max_length=10),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='vad_type',
            field=models.CharField(choices=[('server_vad', 'Server VAD (silence-based)'), ('semantic_vad', 'Semantic VAD (context-based)')], default='server_vad', help_text='Voice activity detection mode', max_length=20),
        ),
        migrations.AlterField(
            model_name='agentconfiguration',
            name='vad_prefix_padding_ms',
            field=models.IntegerField(default=300, help_text='Audio to include before detected speech (milliseconds)'),
        ),
        migrations.AlterField(
            model_name='agentconfiguration',
            name='vad_silence_duration_ms',
            field=models.IntegerField(default=500, help_text='Silence duration to detect speech stop (milliseconds). Shorter = faster turn detection'),
        ),
        migrations.AlterField(
            model_name='agentconfiguration',
            name='vad_threshold',
            field=models.FloatField(default=0.5, help_text='Activation threshold (0-1). Higher = requires louder audio, better for noisy environments'),
        ),
    ]
