# Generated by Django 4.2.7 on 2025-09-18 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_api', '0008_add_instruction_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('call_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='realtime_api.callsession')),
            ],
        ),
        migrations.AlterField(
            model_name='agentconfiguration',
            name='instructions',
            field=models.TextField(blank=True, default='You are a helpful AI assistant named {name}. You can respond with both text and audio. Keep responses concise and natural.', help_text="Instructions for the AI agent. Use {name} as a placeholder for the agent's name. Select a template above to populate this field, then customize as needed."),
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=16)),
                ('text', models.TextField(blank=True, help_text='Complete message text')),
                ('audio_url', models.URLField(blank=True, help_text='URL to audio file if persisted')),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='realtime_api.conversation')),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='e.g., response.output_text.delta', max_length=80)),
                ('event_id', models.CharField(blank=True, help_text='Server-assigned event ID', max_length=128)),
                ('item_id', models.CharField(blank=True, help_text='Conversation item ID', max_length=128)),
                ('response_id', models.CharField(blank=True, help_text='Response ID for grouping deltas', max_length=128)),
                ('role', models.CharField(blank=True, help_text='user | assistant', max_length=16)),
                ('payload', models.JSONField(default=dict, help_text='Raw event data')),
                ('text_delta', models.TextField(blank=True, help_text='Text content for accumulation')),
                ('error', models.TextField(blank=True, help_text='Error message if applicable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='realtime_api.conversation')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'event_type'], name='realtime_ap_convers_9e05a5_idx'), models.Index(fields=['conversation', 'response_id'], name='realtime_ap_convers_c8c32a_idx'), models.Index(fields=['conversation', 'item_id'], name='realtime_ap_convers_e2d0ef_idx')],
            },
        ),
    ]
