# Generated by Django 4.2.7 on 2025-09-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_api', '0009_add_conversation_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfiguration',
            name='mcp_auth_token',
            field=models.CharField(blank=True, help_text='Authentication token for MCP server (optional, will be encrypted)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='mcp_tenant_id',
            field=models.CharField(blank=True, help_text='Tenant ID for MCP server authentication (optional)', max_length=100, null=True),
        ),
    ]
