# Generated by Django 4.2.7 on 2025-09-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_api', '0010_add_mcp_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfiguration',
            name='agent_timezone',
            field=models.CharField(default='UTC', help_text="Agent's timezone for time awareness (e.g., 'America/New_York', 'Europe/London', 'UTC')", max_length=50),
        ),
    ]
