# Generated by Django 4.2.7 on 2025-09-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_api', '0011_add_agent_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfiguration',
            name='idle_timeout_seconds',
            field=models.IntegerField(default=300, help_text='Maximum idle time in seconds before automatically disconnecting the call (0 = no timeout)'),
        ),
    ]
