# Generated by Django 4.2.7 on 2025-09-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_api', '0012_add_idle_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentconfiguration',
            name='vad_prefix_padding_ms',
            field=models.IntegerField(default=300, help_text='Audio to include before detected speech (milliseconds). Higher = captures more context at speech start'),
        ),
        migrations.AlterField(
            model_name='agentconfiguration',
            name='vad_silence_duration_ms',
            field=models.IntegerField(default=500, help_text='Silence duration to detect speech stop (milliseconds). Shorter = faster turn detection, larger = more stable in noisy environments'),
        ),
        migrations.AlterField(
            model_name='agentconfiguration',
            name='vad_threshold',
            field=models.FloatField(default=0.7, help_text='Activation threshold (0.0=sensitive, 1.0=requires loud audio). Higher = requires louder audio, better for noisy environments. Recommended: 0.7'),
        ),
    ]
